import { Inter } from "next/font/google";
import "/public/css/color.css";
import "/public/css/globals.css";
import "/public/css/layout.css";
import Header from "@/component/layout/Header";
import Footer from "@/component/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
